name: Verif FB
on: { workflow_dispatch: {} }
jobs:
  v:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - env: { IG_TOKEN: "${{ secrets.IG_TOKEN }}" }
        run: python verify_fb.py
